name: Clear Cloudflare cache
on: page_build

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: run clear cache script
        run: |
          npm run cf:cache:purge
        env:
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
