name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest master
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Deploy
        run: |
          npm run deploy

      - name: Clear Cloudflare cache
        run: |
          npm run cf:cache:purge
