name: Build and Deploy
on:
  schedule:
    - cron: '0 11 * * *'
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Deploy
        run: |
          git config --global user.email "hello@jabran.me"
          git config --global user.name "Jabran Rafique"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}

      - name: run clear cache script
        run: |
          npm run cf:cache:purge
        env:
          CF_EMAIL: $CF_EMAIL
          CF_TOKEN: $CF_TOKEN
          CF_ZONE_ID: $CF_ZONE_ID
